obj-$(CONFIG_VIDEO_TX_ISP)     += tx_isp.o
obj-$(CONFIG_VIDEO_TX_ISP)     += apical-isp/
obj-$(CONFIG_VIDEO_TX_ISP)     += videoin/

tx_isp-objs :=   txx-funcs.o  tx-isp-debug.o  tx-isp-videobuf.o  \
				 tx-isp-interrupt.o  tx-isp-ncu.o  tx-isp-mscaler.o  \
				 tx-isp-frame-channel.o  tx-isp-device.o      \
				 # apical-isp/apical_isp.o  videoin/videoin.o
