#
# linux/drivers/mtd/devices/ingenic_sfc_v2/Makefile
#


#obj-y	+= ingenic_sfc_common.o ingenic_sfc_nand.o nand_device/ ingenic_sfc_nor.o ingenic_sfc_ops.o ingenic_sfc_drv.o
obj-y += logo.o
obj-y += ingenic_sfc_common.o ingenic_sfc_ops.o
obj-$(CONFIG_OLED_FT2306) += ingenic_sfc_nand.o ingenic_sfc_drv.o
