
obj-y		+= board_base.o
obj-$(CONFIG_USB_JZ_DWC2) += usb_pin.o
obj-$(CONFIG_USB_DWC_OTG) += usb_pin.o
obj-$(CONFIG_JZMMC_V12_MMC0) += mmc.o
obj-$(CONFIG_JZMMC_V12_MMC1) += mmc.o
obj-$(CONFIG_JZ_SFC) += sfc_bus.o
