#ifdef CONFIG_SPL_RTOS_BOOT

#if defined(CONFIG_SPL_MMC_SUPPORT) || defined(CONFIG_SPL_JZMMC_SUPPORT)
#define CONFIG_RTOS_OFFSET (17 * 1024 + CONFIG_SPL_PAD_TO)
#else
#define CONFIG_RTOS_OFFSET CONFIG_SPL_PAD_TO
#endif

#endif
