
obj-y += mic.o
obj-y += mic_sys.o
obj-y += mic_ops.o
obj-y += mic_dma.o
obj-y += mic_hrtimer.o

obj-y += amic.o

obj-y += x1520_codec.o
obj-y += i2s.o
obj-y += dma_ops.o

obj-$(CONFIG_X1520_MIC_SND_INTERNAL_CODEC) += snd_internal_codec.o
obj-$(CONFIG_X1520_MIC_SND_INTERNAL_CODEC) += snd_internal_codec_volume.o
obj-$(CONFIG_X1520_MIC_SND_INTERNAL_CODEC) += snd_hrtimer.o
