#include <libpng/png.h>
#include <stdlib.h>
#include <stdio.h>

void gen_info(int w, int h, int bpp, int backcolor)
{
	printf("/*\n"
			" * Automatically generated by \"mklogo\"\n"
			" *\n"
			" * DO NOT EDIT\n"
			" *\n"
			" */\n\n"
			"#include <video/ingenic_logo.h>\n\n"
			"extern unsigned char logo_buf[];\n\n"
			"struct _logo_info logo_info = {\n"
			"\t%d,\n"
			"\t%d,\n"
			"\t%d,\n"
			"\tlogo_buf,\n"
			"\t0x%08x,\n"
			"};\n\n"
			"unsigned char logo_buf[] = {\n",
			w, h, bpp, backcolor);
}

void ReadPng(const char *png_file, int real_bit_dep ,int backcolor)
{
	int i, j, k = 0;
	FILE *file = fopen(png_file, "rb");

	// create read struct
	png_structp png_ptr = png_create_read_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);

	// create info struct
	png_infop info_ptr = png_create_info_struct(png_ptr);

	setjmp(png_jmpbuf(png_ptr));                              //设置错误的返回点

	// I/O initialization using standard C streams
	png_init_io(png_ptr, file);

	// read entire image , ignore alpha channel
	png_read_png(png_ptr, info_ptr, PNG_TRANSFORM_EXPAND, NULL);
	/* int width  = info_ptr->width; */
	/* int height = info_ptr->height; */
	/* int color_type = info_ptr->color_type; */
	/* int bit_dep = info_ptr->pixel_depth; */
	/* printf("\033[31m width = %d | height = %d | color_type = %d | bit_dep = %d |\033[0m\n", width, height, color_type, bit_dep); */

	// read pic data
	unsigned int pixel_num = info_ptr->height * info_ptr->width;

	png_bytep* row_pointers = png_get_rows(png_ptr, info_ptr);

	// gen head file.
	gen_info(info_ptr->width, info_ptr->height, real_bit_dep, backcolor);

	if(real_bit_dep == 32) {
		for(i = 0; i < info_ptr->height; i++)
		{
			for(j = 0; j < (4 * info_ptr->width); j += 4)
			{
				printf (" 0x%02X, 0x%02X, 0x%02X, 0x%02X,%s",
						row_pointers[i][j + 2], row_pointers[i][j + 1],
						row_pointers[i][j], row_pointers[i][j + 3],
						((k++%8) == 7) ? "\n" : "");
			}
		}

	} else if(real_bit_dep == 16) {
		unsigned short s16;
		for(i = 0; i < info_ptr->height; i++)
		{
			for(j = 0; j < (4 * info_ptr->width); j += 4)
			{
				s16 = ((row_pointers[i][j] & 0xf8) << 8)
					| ((row_pointers[i][j + 1] & 0xfc) << 3)
					| ((row_pointers[i][j + 2] & 0xf8) >> 3);
				unsigned char *p8 = (unsigned char*)&s16;
				printf (" 0x%02X, 0x%02X,%s", p8[0], p8[1], ((k++%8) == 7) ? "\n" : "");
			}
		}
	}

printf("};\n");

// free memory
png_destroy_read_struct(&png_ptr, &info_ptr, 0);

// close file
fclose(file);
}

int main(int argc, char *argv[])
{
	int backcolor = 0x00000000;

	if (argc == 4)
		sscanf(argv[3], "%x", &backcolor);

	if (argc >= 3)
		ReadPng(argv[1], atoi(argv[2]), backcolor);
	 else {
		printf("usage: png2logo --pngfile --bpp<32|16> [--backcolor]\n");
		printf("       e.x.: png2logo logo.png 32 0x000000ff > logo.c\n");
	}

	return 0;
}
