## X1000 Supported Boards
snd_x1000-board-y := x1000-board.o
obj-$(CONFIG_SND_ASOC_INGENIC_X1000_BOARD) += snd_x1000-board.o
## X2000 Supported Boards
snd_seal-y := seal.o
obj-$(CONFIG_SND_ASOC_INGENIC_SEAL) += snd_seal.o

## X2000 v12 Supported Boards
snd_zebra-y := zebra.o
obj-$(CONFIG_SND_ASOC_INGENIC_ZEBRA) += snd_zebra.o
snd_zebra_dmic_icdc-y := zebra_dmic_icdc.o
obj-$(CONFIG_SND_ASOC_INGENIC_ZEBRA_DMIC_ICDC) += snd_zebra_dmic_icdc.o
snd_halley5_v20-y := halley5_v20.o
obj-$(CONFIG_SND_ASOC_INGENIC_HALLEY5_V20) += snd_halley5_v20.o
snd_gewu-y := gewu.o
obj-$(CONFIG_SND_ASOC_INGENIC_GEWU) += snd_gewu.o
snd_kale_v10-y := kale_v10.o
obj-$(CONFIG_SND_ASOC_INGENIC_KALE) += snd_kale_v10.o

## darwin Supported Boards
snd_darwin-board-y := darwin-board.o
obj-$(CONFIG_SND_ASOC_INGENIC_DARWIN_BOARD) += snd_darwin-board.o

## hippo Supported Boards
snd_hippo-board-y := hippo-board.o
obj-$(CONFIG_SND_ASOC_INGENIC_HIPPO_BOARD) += snd_hippo-board.o
## smartpen knot Supported Boards
snd_x2500_knot-board-y := x2500-knot.o
obj-$(CONFIG_SND_ASOC_INGENIC_KNOT_BOARD) += snd_x2500_knot-board.o

## x1600 Supported Boards
snd_panda-y := panda.o
obj-$(CONFIG_SND_ASOC_INGENIC_PANDA) += snd_panda.o
snd_halley6-y := halley6.o
obj-$(CONFIG_SND_ASOC_INGENIC_HALLEY6) += snd_halley6.o
snd_x1600_iris-y := x1600_iris.o
obj-$(CONFIG_SND_ASOC_INGENIC_X1600_IRIS) += snd_x1600_iris.o
