## WARNING! DO NOT change this lists order because power sleep order depends on it!! ##
obj-y += setup.o
obj-y += reset.o
obj-y += timer_sys_ost.o
obj-y += serial.o
obj-y += clk/
obj-y += gpio.o
obj-y += irq.o
obj-y += cpm_usb.o
obj-y += platform.o
obj-y += libdmmu.o
obj-y += ddr.o
obj-y += proc.o
obj-y += tcu.o
# only for debug
#obj-y += pmmon.o

obj-y += pm.o
#obj-y += ahbm.o
