# Makefile for the focaltech touchscreen drivers.
#EXTRA_CFLAGS  +=-Wno-error=date-time
EXTRA_CFLAGS  += -Wno-date-time
obj-$(CONFIG_TOUCHSCREEN_GT9XX_V2)	+=  gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_V2)	+=  gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_V2)	+=  goodix_tool.o
