
obj-$(CONFIG_MACH_JZ4740)	+= legency/
obj-$(CONFIG_MACH_JZ4780)	+= legency/
obj-$(CONFIG_COMMON_CLK_INGENIC)	+= clk-comm.o clk-cpccr.o clk-cgu.o clk-gate.o
obj-$(CONFIG_SOC_X1000)		+= clk-x1000.o clk-rtc.o clk-pll.o
obj-$(CONFIG_SOC_X1800)		+= clk-x1800.o clk-rtc.o clk-pll-v2.o
obj-$(CONFIG_SOC_X1021)		+= clk-x1021.o clk-rtc.o clk-pll-v2.o
obj-$(CONFIG_SOC_X1520)		+= clk-x1520.o clk-rtc.o clk-pll-v2.o
obj-$(CONFIG_SOC_X1630)		+= clk-x1630.o clk-rtc.o clk-pll-v2.o
obj-$(CONFIG_SOC_X2000)		+= clk-x2000.o clk-x2000-cgu-audio.o clk-pll.o
