ingenic_fb_v12-y := ingenicfb.o\
			jz_mipi_dsi/jz_mipi_dsi.o\
			jz_mipi_dsi/jz_mipi_dsi_lowlevel.o\
			jz_mipi_dsi/jz_mipi_dsih_hal.o
obj-$(CONFIG_FB_INGENIC_V12) += ingenic_fb_v12.o
obj-y += displays/
