CFLAGS_KERNEL   += -I$(srctree)/arch/mips/xburst/soc-4775/chip-4775/$(CONFIG_PRODUCT_NAME)/$(CONFIG_BOARD_NAME)


obj-$(CONFIG_BOARD_MANSA_V12)       += common/
obj-$(CONFIG_BOARD_MANSA_V20)       += common_v20/
obj-y      += $(CONFIG_BOARD_NAME)/
