
CFLAGS_KERNEL	+= -I$(srctree)/arch/mips/xburst/soc-m200/chip-m200/$(CONFIG_PRODUCT_NAME)/$(CONFIG_BOARD_NAME)
CFLAGS_MODULE	+= -I$(srctree)/arch/mips/xburst/soc-m200/chip-m200/$(CONFIG_PRODUCT_NAME)/$(CONFIG_BOARD_NAME)

obj-y		+= common/
obj-$(CONFIG_BOARD_HALLEY2_PRO_V10)		+= $(CONFIG_BOARD_NAME)/
