#!/bin/bash
    SSV_DRV_PATH=/home/robin/work/X2000/module_driver/devices/wireless/ssv6x5x_linux
    KERNEL_OBJ_PATH=/home/robin/work/X2000/kernel/kernel-x2000
    #INSTALL_PATH=kernel/drivers/net/wireless/ssv6200
    PLATFORM_TOOLCHAIN=/home/robin/work/X2000/tools/toolchains/mips-gcc520-glibc222/bin/mips-linux-gnu-
    PLATFORM_ARCH=mips

    make -C $SSV_DRV_PATH KERNEL_OBJ_PATH=$KERNEL_OBJ_PATH SSV_DRV_PATH=$SSV_DRV_PATH ARCH=$PLATFORM_ARCH CROSS_COMPILE=$PLATFORM_TOOLCHAIN clean
    make -C $SSV_DRV_PATH KERNEL_OBJ_PATH=$KERNEL_OBJ_PATH SSV_DRV_PATH=$SSV_DRV_PATH ARCH=$PLATFORM_ARCH CROSS_COMPILE=$PLATFORM_TOOLCHAIN modules
    make -C $SSV_DRV_PATH SSV_DRV_PATH=$SSV_DRV_PATH CROSS_COMPILE=$PLATFORM_TOOLCHAIN strip
    #make -C $SSV_DRV_PATH KERNEL_OBJ_PATH=$KERNEL_OBJ_PATH SSV_DRV_PATH=$SSV_DRV_PATH INSTALL_PATH=$INSTALL_PATH install