#!/bin/sh

jpeg_display()
{
    while true
    do
        if [ -e "/dev/fb0" ]; then
            break
        fi
        sleep 0.02
    done

    cmd_jpeg_display /etc/logo.jpeg
}

case "$1" in
    start)
        jpeg_display &

    ;;
    *)
        exit 1
esac

exit 0
