obj-$(CONFIG_SND_SOC_SY6026L)		+= sy6026l.o
obj-$(CONFIG_I2C_GPIO)			+= gpio.o
obj-$(CONFIG_SI1143)			+= si1143.o
obj-$(CONFIG_AW9163)			+= aw9163.o
obj-$(CONFIG_AW87519)           += aw87519.o
obj-$(CONFIG_SENSORY_LICENSE)	+= sensory_license.o
obj-$(CONFIG_GSL1680)           += gsl1680.o
obj-$(CONFIG_TOUCHSCREEN_GT917S)               += gt917S_boards.o
