
obj-y		+= board_base.o
obj-y		+= misc.o
obj-$(CONFIG_JZMMC_V12)		+= mmc.o
obj-$(CONFIG_KEYBOARD_GPIO)	+= keyboard_gpio.o

obj-$(CONFIG_BCM_PM_CORE)   += bcm_power_control.o
obj-$(CONFIG_SOUND_OSS_XBURST)		+= sound.o
obj-$(CONFIG_I2C_GPIO)			+= i2c_bus.o
obj-$(CONFIG_I2C0_V12_JZ)		+= i2c_bus.o
obj-$(CONFIG_I2C1_V12_JZ)		+= i2c_bus.o
obj-$(CONFIG_JZ_SPI) += spi_bus.o
obj-$(CONFIG_JZ_SFC) += sfc_bus.o
obj-$(CONFIG_SPI_GPIO) += spi_bus.o
obj-$(CONFIG_VIDEO_TX_ISP)	+= tx_isp.o
obj-y +=lcd/
