#define CONFIG_MIPS32
#define CONFIG_CPU_XBURST
#define CONFIG_SYS_LITTLE_ENDIAN
#define CONFIG_X1630
#define CONFIG_SYS_EXTAL        24000000
#define CONFIG_SYS_HZ           1000

#define CONFIG_SYS_DCACHE_SIZE        32768
#define CONFIG_SYS_ICACHE_SIZE        32768
#define CONFIG_SYS_CACHELINE_SIZE    32

#ifndef CONFIG_SYS_UART_INDEX
#define CONFIG_SYS_UART_INDEX 1
#endif

#ifndef CONFIG_BAUDRATE
#define CONFIG_BAUDRATE 3000000
#endif
