obj-y			+= common/
obj-y			+= debug/
obj-$(CONFIG_SOC_X1000) += soc-x1000/
obj-$(CONFIG_SOC_X1800) += soc-x1800/
obj-$(CONFIG_SOC_X1021) += soc-x1021/
obj-$(CONFIG_SOC_X1520) += soc-x1520/
obj-$(CONFIG_SOC_X1600) += soc-x1600/
obj-$(CONFIG_SOC_X1630) += soc-x1630/
