obj-$(CONFIG_VIDEO_INGENIC_ISP) += ingenic-isp/
obj-$(CONFIG_VIDEO_INGENIC_ISP_V2) += ingenic-isp-v2/
obj-$(CONFIG_VIDEO_INGENIC_ROTATE) 		+= ingenic-rotate/
obj-$(CONFIG_VIDEO_INGENIC_VCODEC)	+= ingenic-vcodec/
obj-$(CONFIG_VIDEO_INGENIC_JPEG)  += ingenic-jpeg/
obj-$(CONFIG_SOC_CAMERA)		+= soc_camera/
obj-$(CONFIG_INGENIC_I2D)		+= ingenic-i2d/
